package BCT;

public enum BCT_NodeType {
	APPLICATION, BUILTIN, CONSTANT_NUM, CONSTANT_STRING, CONSTANT_BOOL, MINUS, PLUS, DIV, MUL, HD, TL, 
	AND, OR, NOT, COND, EQ, NEQ, LT, GT, LEQ, GEQ, S, K ,I, Y, U, B, C, S_, B_, C_, VAR, COLON, NIL, PAIR;
}
